importScripts("../Library/SW/SW.js");

cacheManager({
	name:"Coordinates",
	build:[2019,11,17],
	list:[
		"Coord.html",
		"resources/style.css",
		"resources/menu.css",
		"resources/core.js",
		"resources/calc.js",
		"resources/canvas.js",
		"resources/svg.js",
		"resources/input.js",
		"resources/menu.js",
		"resources/status.js",
		"resources/mask.svg",
		"resources/icon.png",
		"resources/favicon.ico",
		"resources/apple-touch-icon.png",
		"resources/tileImage.png",
		"manifest.json"
	]
});